// <auto-generated />
using System;
using CalculatriceLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculatriceLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CalculatriceLibrary.Models.CalculationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expression")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Operand1")
                        .HasColumnType("REAL");

                    b.Property<double?>("Operand2")
                        .HasColumnType("REAL");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Result")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CalculationLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Expression = "10+5",
                            Operand1 = 10.0,
                            Operand2 = 5.0,
                            Operator = "+",
                            Result = 15.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 9, 1, 0, 0, DateTimeKind.Unspecified),
                            Expression = "100-37",
                            Operand1 = 100.0,
                            Operand2 = 37.0,
                            Operator = "-",
                            Result = 63.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 9, 2, 0, 0, DateTimeKind.Unspecified),
                            Expression = "7*8",
                            Operand1 = 7.0,
                            Operand2 = 8.0,
                            Operator = "*",
                            Result = 56.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 9, 3, 0, 0, DateTimeKind.Unspecified),
                            Expression = "144/12",
                            Operand1 = 144.0,
                            Operand2 = 12.0,
                            Operator = "/",
                            Result = 12.0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 9, 4, 0, 0, DateTimeKind.Unspecified),
                            Expression = "9^2",
                            Operand1 = 9.0,
                            Operator = "pow2",
                            Result = 81.0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            Expression = "2^10",
                            Operand1 = 2.0,
                            Operand2 = 10.0,
                            Operator = "powN",
                            Result = 1024.0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 20, 9, 6, 0, 0, DateTimeKind.Unspecified),
                            Expression = "sqrt(256)",
                            Operand1 = 256.0,
                            Operator = "sqrt",
                            Result = 16.0
                        });
                });

            modelBuilder.Entity("CalculatriceLibrary.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CalculatriceLibrary.Models.CalculationLog", b =>
                {
                    b.HasOne("CalculatriceLibrary.Models.User", "User")
                        .WithMany("Calculations")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalculatriceLibrary.Models.User", b =>
                {
                    b.Navigation("Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
